#!/bin/bash

CFLAGS='-Wall -Wextra -Wpedantic -std=c99'

function buildg {    # Build debug
  gcc $CFLAGS -g vm.c -o vm
}
function buildf {    # Build fast
  musl-clang $CFLAGS  -Ofast -flto -static vm.c -o vm
  musl-gcc $CFLAGS -Ofast -fwhole-program -static vm.c -o vm_mg
}

function test {    # Run tests
  gcc -DTEST $CFLAGS -g vm.c -o vm
  ./vm
}

function check {
  gcc $CFLAGS -g vm.c -o vm
  ./vm StackArithmetic/SimpleAdd/SimpleAdd.vm
  ./vm MemoryAccess/BasicTest/BasicTest.vm
  ./vm StackArithmetic/StackTest/StackTest.vm

}

function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
