#!/bin/bash

function clean {    # Clean things
    echo "Cleaning"
}

function build {    # Build stuff
  for v in Math String Array Memory Screen Output Keyboard Sys
  do
    cp "${v}.jack" "${v}Test/"
    ../../tools/JackCompiler.sh "${v}Test"
  done

  cp Memory.jack MemoryTest/MemoryDiag/
  ../../tools/JackCompiler.sh MemoryTest/MemoryDiag

  cp *.jack Pong/
  ../../tools/JackCompiler.sh Pong
}

function run {    # Runs something
  echo "Run"
}

function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
