#!/bin/bash

CFLAGS='-Wall -Wextra -Wpedantic -std=c99'

function perf {     # Perf test
  hyperfine --warmup 5 "./assembler pong/pong.asm" "./rustassembler pong/pong.asm" "java HackAssembler pong/pong.asm" "python python/Assembler.py pong/pong.asm"
}

function lc {       # Count lines of code
  wc -l assembler.c
  wc -l rust/*.rs
  wc -l java/*.java
  wc -l python/*.py
}

function check {    # Diff 2 assemblers
  assemble
  diff -s ./add/Add.hack ./add/Add.asm.hack
  diff -s ./max/MaxL.hack ./max/MaxL.asm.hack
  diff -s ./rect/RectL.hack ./rect/RectL.asm.hack
  diff -s ./pong/PongL.hack ./pong/PongL.asm.hack

  diff -s ./max/Max.hack ./max/Max.asm.hack
  diff -s ./rect/Rect.hack ./rect/Rect.asm.hack
  diff -s ./pong/Pong.hack ./pong/Pong.asm.hack
}

function buildg {    # Build debug
  gcc $CFLAGS -g assembler.c -o assemblerg
}

function test {      # Run the tests
  musl-clang $CFLAGS -DTEST -g -static assembler.c -o assembler
  ./assembler
}
function buildf {    # Build fast
  musl-clang $CFLAGS  -Ofast -flto -static assembler.c -o assembler
  musl-gcc $CFLAGS  -Ofast -fwhole-program -static assembler.c -o assembler_gcc
}
function assemble {    # assemble
  buildf
  ./assembler add/Add.asm
  ./assembler max/MaxL.asm
  ./assembler rect/RectL.asm
  ./assembler pong/PongL.asm

  ./assembler max/Max.asm
  ./assembler rect/Rect.asm
  ./assembler pong/Pong.asm

  ../../tools/Assembler.sh add/Add.asm
  ../../tools/Assembler.sh max/MaxL.asm
  ../../tools/Assembler.sh rect/RectL.asm
  ../../tools/Assembler.sh pong/PongL.asm

  ../../tools/Assembler.sh max/Max.asm
  ../../tools/Assembler.sh rect/Rect.asm
  ../../tools/Assembler.sh pong/Pong.asm
}

function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
