#!/bin/bash

function check {    # Diff 2 assemblers
  assemble
  diff -s ./add/Add.hack ./add/Add.asm.hack
  diff -s ./max/MaxL.hack ./max/MaxL.asm.hack
  diff -s ./rect/RectL.hack ./rect/RectL.asm.hack
  diff -s ./pong/PongL.hack ./pong/PongL.asm.hack

  diff -s ./max/Max.hack ./max/Max.asm.hack
}

function buildg {    # Build debug
  gcc -g assembler.c -o assembler
}

function test {      # Run the tests
  musl-clang -DTEST -g -static assembler.c -o assembler
  ./assembler
}
function buildf {    # Build fast
  musl-clang -Ofast -flto -static assembler.c -o assembler
  musl-gcc -Ofast -fwhole-program -static assembler.c -o assembler_mg
}
function assemble {    # assemble
  buildf
  ./assembler add/Add.asm
  ./assembler max/MaxL.asm
  ./assembler rect/RectL.asm
  ./assembler pong/PongL.asm
  ./assembler max/Max.asm

  ../../tools/Assembler.sh add/Add.asm
  ../../tools/Assembler.sh max/MaxL.asm
  ../../tools/Assembler.sh rect/RectL.asm
  ../../tools/Assembler.sh pong/PongL.asm
  ../../tools/Assembler.sh max/Max.asm
}

function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
