#!/bin/bash

CFLAGS='-Wall -Wextra -Wpedantic -std=c99'

function buildg {    # Build debug
  gcc $CFLAGS -g JackCompiler.c -o JackCompiler
}
function buildf {    # Build fast
  musl-clang $CFLAGS  -Ofast -flto -static JackCompiler.c -o JackCompiler_cl
  musl-gcc $CFLAGS -Ofast -fwhole-program -static JackCompiler.c -o JackCompiler_mg
}

function test {    # Run tests
  gcc -DTEST $CFLAGS -g JackCompiler.c -o JackCompiler
  ./JackCompiler
}

function check {
  buildg
  ./JackCompiler ProgramFlow/BasicLoop/BasicLoop.JackCompiler
  ./JackCompiler ProgramFlow/FibonacciSeries/FibonacciSeries.JackCompiler
  ./JackCompiler FunctionCalls/FibonacciElement/*.JackCompiler
  mv FunctionCalls/FibonacciElement/out.asm FunctionCalls/FibonacciElement/FibonacciElement.asm
  ./JackCompiler FunctionCalls/StaticsTest/*.JackCompiler
  mv FunctionCalls/StaticsTest/out.asm FunctionCalls/StaticsTest/StaticsTest.asm
  ./JackCompiler FunctionCalls/NestedCall/*.JackCompiler
  mv FunctionCalls/NestedCall/out.asm FunctionCalls/NestedCall/NestedCall.asm
}

function lc {       # Count lines of code
  wc -l JackCompiler.c
  wc -l rust/*.rs
  wc -l java/*.java
}

function perf {   # Perf test
  hyperfine --warmup 5 "./JackCompiler_cl FunctionCalls/FibonacciElement/*.JackCompiler" "./JackCompiler_mg FunctionCalls/FibonacciElement/*.JackCompiler" "./rustJackCompiler FunctionCalls/FibonacciElement" "java JackCompilertranslator FunctionCalls/FibonacciElement"
}

function memrust {    # Test memory consumption
  valgrind --tool=massif --massif-out-file=rustJackCompiler.massif --stacks=yes  ./rustJackCompiler FunctionCalls/FibonacciElement
  ms_print rustJackCompiler.massif | bat
}
function memc {    # Test memory consumption
  valgrind --tool=massif --massif-out-file=JackCompiler_cl.massif --stacks=yes  ./JackCompiler_cl FunctionCalls/FibonacciElement/*.JackCompiler
  ms_print JackCompiler_cl.massif | bat
}
function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
