#!/bin/bash

CFLAGS='-Wall -Wextra -Wpedantic -std=c99'

function buildg {    # Build debug
  gcc $CFLAGS -g vm.c -o vm
}
function buildf {    # Build fast
  musl-clang $CFLAGS  -Ofast -flto -static vm.c -o vm_cl
  musl-gcc $CFLAGS -Ofast -fwhole-program -static vm.c -o vm_mg
}

function test {    # Run tests
  gcc -DTEST $CFLAGS -g vm.c -o vm
  ./vm
}

function check {
  buildg
  ./vm ProgramFlow/BasicLoop/BasicLoop.vm
  ./vm ProgramFlow/FibonacciSeries/FibonacciSeries.vm
  ./vm FunctionCalls/FibonacciElement/*.vm
  mv FunctionCalls/FibonacciElement/out.asm FunctionCalls/FibonacciElement/FibonacciElement.asm
  ./vm FunctionCalls/StaticsTest/*.vm
  mv FunctionCalls/StaticsTest/out.asm FunctionCalls/StaticsTest/StaticsTest.asm
  ./vm FunctionCalls/NestedCall/*.vm
  mv FunctionCalls/NestedCall/out.asm FunctionCalls/NestedCall/NestedCall.asm
}

function lc {       # Count lines of code
  wc -l vm.c
  wc -l rust/*.rs
  wc -l java/*.java
}

function perf {   # Perf test
  hyperfine --warmup 5 "./vm_cl FunctionCalls/FibonacciElement/*.vm" "./vm_mg FunctionCalls/FibonacciElement/*.vm" "./rustvm FunctionCalls/FibonacciElement" "java VMtranslator FunctionCalls/FibonacciElement"
}

function memrust {    # Test memory consumption
  valgrind --tool=massif --massif-out-file=rustvm.massif --stacks=yes  ./rustvm FunctionCalls/FibonacciElement
  ms_print rustvm.massif | bat
}
function memc {    # Test memory consumption
  valgrind --tool=massif --massif-out-file=vm_cl.massif --stacks=yes  ./vm_cl FunctionCalls/FibonacciElement/*.vm
  ms_print vm_cl.massif | bat
}
function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
